export const Mocktoptracks = [
  {
    streamable: [Object],
    mbid: '60007f05-9c37-4d22-aef4-fcaf0f40b151',
    name: 'Amava Porra Nenhuma',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Amava+Porra+Nenhuma',
    duration: '145',
    '@attr': [Object],
    playcount: '40'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Oi, Como Ce Tá?',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Vulgo+FK/_/Oi,+Como+Ce+T%C3%A1%3F',
    duration: '156',
    '@attr': [Object],
    playcount: '31'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'fim de semana no rio',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Teto/_/fim+de+semana+no+rio',
    duration: '165',
    '@attr': [Object],
    playcount: '28'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Lágrimas De Crocodilo',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/WIU/_/L%C3%A1grimas+De+Crocodilo',
    duration: '196',
    '@attr': [Object],
    playcount: '28'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'M4',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Teto/_/M4',
    duration: '170',
    '@attr': [Object],
    playcount: '26'
  },
  {
    streamable: [Object],
    mbid: '0e9f5e7b-cf83-4123-9df7-b89e7aaa4e73',
    name: 'CYANIDE',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Daniel+Caesar/_/CYANIDE',
    duration: '197',
    '@attr': [Object],
    playcount: '25'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Efeito Borboleta',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Aimar/_/Efeito+Borboleta',
    duration: '152',
    '@attr': [Object],
    playcount: '24'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Rubi',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Aldeia+Records/_/Rubi',
    duration: '207',
    '@attr': [Object],
    playcount: '24'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Kpooper Me Cancelou',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Rapxis/_/Kpooper+Me+Cancelou',
    duration: '0',
    '@attr': [Object],
    playcount: '24'
  },
  {
    streamable: [Object],
    mbid: '2cf96f14-cf32-4af7-a4a6-5eb537ef91e1',
    name: 'Cabeça Branca',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Cabe%C3%A7a+Branca',
    duration: '147',
    '@attr': [Object],
    playcount: '23'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'clown',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Updog/_/clown',
    duration: '137',
    '@attr': [Object],
    playcount: '23'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Volta Vai',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Kevi+Jonny/_/Volta+Vai',
    duration: '184',
    '@attr': [Object],
    playcount: '22'
  },
  {
    streamable: [Object],
    mbid: '1a2031ec-778d-4367-ab5c-2d620ec3d65d',
    name: 'Hackearam-me',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Hackearam-me',
    duration: '209',
    '@attr': [Object],
    playcount: '22'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Vampiro',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Matu%C3%AA/_/Vampiro',
    duration: '0',
    '@attr': [Object],
    playcount: '21'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Tipo Sasori',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/MHRAP/_/Tipo+Sasori',
    duration: '201',
    '@attr': [Object],
    playcount: '21'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Loca',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/AL3JANDRO/_/Loca',
    duration: '206',
    '@attr': [Object],
    playcount: '20'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Dollar',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Only/_/Dollar',
    duration: '160',
    '@attr': [Object],
    playcount: '20'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Eu não falo de meninas pois todas meninas me lembram você',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/D$+Luqi/_/Eu+n%C3%A3o+falo+de+meninas+pois+todas+meninas+me+lembram+voc%C3%AA',
    duration: '163',
    '@attr': [Object],
    playcount: '19'
  },
  {
    streamable: [Object],
    mbid: 'fbde2388-f3d6-4b16-86f2-b9f98f1e3156',
    name: 'everything sucks',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/VaultBoy/_/everything+sucks',
    duration: '0',
    '@attr': [Object],
    playcount: '19'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Enemy (with JID) - from the series Arcane League of Legends',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Imagine+Dragons/_/Enemy+(with+JID)+-+from+the+series+Arcane+League+of+Legends',
    duration: '173',
    '@attr': [Object],
    playcount: '18'
  },
  {
    streamable: [Object],
    mbid: '2bdfc492-9874-4b4c-a548-bebd1e0dfb93',
    name: 'Baggage',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Rare+Americans/_/Baggage',
    duration: '179',
    '@attr': [Object],
    playcount: '18'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Mustang Preto',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Teto/_/Mustang+Preto',
    duration: '183',
    '@attr': [Object],
    playcount: '18'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'A Bela e a Fera',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Xam%C3%A3/_/A+Bela+e+a+Fera',
    duration: '208',
    '@attr': [Object],
    playcount: '18'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Groupies',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/DooDe/_/Groupies',
    duration: '0',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'ama o jeito que me odeia',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Sidoka/_/ama+o+jeito+que+me+odeia',
    duration: '182',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Quadro',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Sidoka/_/Quadro',
    duration: '170',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '344bab06-5aff-41b3-9f22-a83d35f5b232',
    name: 'Rita',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Rita',
    duration: '161',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'fukashigi no carte lofi (bunny girl senpai)',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/tills+chills/_/fukashigi+no+carte+lofi+(bunny+girl+senpai)',
    duration: '150',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'polaroid',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/YUNG+LIXO/_/polaroid',
    duration: '182',
    '@attr': [Object],
    playcount: '17'
  },
  {
    streamable: [Object],
    mbid: '0979fd54-493b-4450-ac27-3bdc1979236d',
    name: 'Train',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Brick%252BMortar/_/Train',
    duration: '185',
    '@attr': [Object],
    playcount: '16'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Recente Demais - Ao Vivo',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Douglas+&+Vinicius/_/Recente+Demais+-+Ao+Vivo',
    duration: '0',
    '@attr': [Object],
    playcount: '16'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Mds',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Kawe/_/Mds',
    duration: '125',
    '@attr': [Object],
    playcount: '16'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Batidão Do Suicídio',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Luckhaos/_/Batid%C3%A3o+Do+Suic%C3%ADdio',
    duration: '141',
    '@attr': [Object],
    playcount: '16'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Era Tu',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Era+Tu',
    duration: '128',
    '@attr': [Object],
    playcount: '16'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'My Heart, My Queen',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/AL3JANDRO/_/My+Heart,+My+Queen',
    duration: '222',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Saturno',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Burn-O/_/Saturno',
    duration: '257',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'É a união FLASCO',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Luckhaos/_/%C3%89+a+uni%C3%A3o+FLASCO',
    duration: '139',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Sorvete de Ovomaltine',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Magyn/_/Sorvete+de+Ovomaltine',
    duration: '131',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Drip da Roça',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/REID/_/Drip+da+Ro%C3%A7a',
    duration: '0',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '28458e91-fc49-42c4-82f4-96b5e179fa86',
    name: 'PayPal',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Teto/_/PayPal',
    duration: '0',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Eu To Com uma Puta',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Tierry/_/Eu+To+Com+uma+Puta',
    duration: '175',
    '@attr': [Object],
    playcount: '15'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Skyfall',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/AL3JANDRO/_/Skyfall',
    duration: '132',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Matches - Subtact Remix',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Ephixa/_/Matches+-+Subtact+Remix',
    duration: '0',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Atoa',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Linear/_/Atoa',
    duration: '0',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Bars No Jutsu',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Louis+Capone/_/Bars+No+Jutsu',
    duration: '0',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'E-Girl',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/LUCAS+HYPE/_/E-Girl',
    duration: '0',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Melhor Dia 7 - Sossego',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Marcos+Baroni/_/Melhor+Dia+7+-+Sossego',
    duration: '318',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Diamante',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/mc+zoio+de+gato/_/Diamante',
    duration: '125',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'Sente a Vibe',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/mc+zoio+de+gato/_/Sente+a+Vibe',
    duration: '151',
    '@attr': [Object],
    playcount: '14'
  },
  {
    streamable: [Object],
    mbid: '',
    name: 'A Lua - Spotify Singles',
    image: [Array],
    artist: [Object],
    url: 'https://www.last.fm/music/Teto/_/A+Lua+-+Spotify+Singles',
    duration: '159',
    '@attr': [Object],
    playcount: '14'
  }
]
